spring.application.name=present-project

jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=${JWT_EXPIRATION_TIME}


# 1. ?????????? ??????????? (DataSource)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_name
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver



# 2. ????????? Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database=postgresql

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.data.web.pageable.one-indexed-parameters=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.messages.basename=lang/messages
spring.messages.encoding=UTF-8