spring.application.name=xojainka

# 1. ?????????? ??????????? (DataSource)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_name
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver



# 2. ????????? Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database=postgresql

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.data.web.pageable.one-indexed-parameters=true
